services:
  patlytics-inf-api:
    container_name: patlytics-inf-api
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      BASE_PATH: ${BASE_PATH}
      PORT: ${PORT}
      RATE_LIMIT: ${RATE_LIMIT}
      TRUST_PROXY: ${TRUST_PROXY}
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      DB_MYSQL_USERNAME: ${DB_MYSQL_USERNAME}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      OPENAI_LLM_API_KEY: ${OPENAI_LLM_API_KEY}
    ports:
      - "8060:8060"
    networks:
      - docker_default


  patlytics-inf-mysql:
    image: mysql:8.0
    container_name: patlytics-inf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
    ports:
      - "3306"
    volumes:
      - patlytics-inf-mysql-data:/var/lib/mysql
    networks:
      - docker_default

  patlytics-inf-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: patlytics-inf-phpmyadmin
    environment:
      PMA_HOST: ${DB_MYSQL_HOST}
      PMA_USER: ${DB_MYSQL_USERNAME}
      PMA_PASSWORD: ${DB_MYSQL_PASSWORD}
    ports:
      - "7053:80"
    depends_on:
      - patlytics-inf-mysql
    networks:
      - docker_default

volumes:
  patlytics-inf-mysql-data:

networks:
  docker_default:
    driver: bridge
    name: ${DOCKER_NETWORK_NAME}