name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build --build-arg BASE_PATH=/api -t ${{ secrets.DOCKER_USERNAME }}/patlytics-inf-api:main -f Dockerfile.remote .
        docker push ${{ secrets.DOCKER_USERNAME }}/patlytics-inf-api:main
